### ISSUE TITLE
Why Linux only?

### ISSUE THREAD

**Issue by MystPi** [JaydenDev/community-scripts#1]
Like it or not, most of the world uses Windows or Mac.

**Comment by jdev082** [comment]
They use Linux commands and libraries. Plus I abandoned this repo.

**Comment by MystPi** [comment]
Already?

**Comment by jdev082** [comment]
The scripts I don't need cuz they solve problems I don't have anymore. Plus, I have bigger more important repositories to maintain. Such as FreeCat.
